# -*- coding: utf-8 -*-
"""convite1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAYCsrwiHdLRxAetZKyPYAqxR0_vigFN
"""

import time
import webbrowser

def introducao():
  print("Você gosta de filmes com drama envolvido? Se sim, essa mensagem pode ser para você!")
  time.sleep(1)
  print("\nDeseja continuar? (Sim/Não)")
  escolha = input().strip().lower()
  return escolha

def exibir_trailer():
  print("\nAqui está o trailer do filme que estou sugerindo para você.")
  time.sleep(2)
  print("Aguarde alguns instantes...")
  trailer_url = "https://youtu.be/MxnQhCUhltU?si=wL4KDy9QdMe5mvF8"
  print(f"\nClique no link abaixo para assistir ao trailer :)")
  print(trailer_url)
  time.sleep(1)
  print("\nQuando terminar de assistir ao trailer do filme, pressione Enter para continuar.")
  input()

def pergunta_final():
  print("\nAgora que você assistiu ao trailer, o que você acha de irmos assistir com bastante pipoca envolvida e direito a lágrimas?")
  time.sleep(1)
  print("\nEscolha uma das opções a seguir:")
  print("1 - Quero muito! Já vou separar o lencinho.")
  print("2 - Eu topo!")
  print("3 - Deixa pra próxima.")

  resposta = input().strip()
  return resposta

def resposta_final(resposta):
  if resposta == "1":
    print("\nTá fechado então! S2")
  elif resposta == "2":
    print("\nLegal vamos agendar então!")
  elif resposta == "3":
    print("\nNão tem problema!")
  else:
    print("\nResposta inválida. Tente novamente.")

def main():
  escolha_inicial = introducao()

  if escolha_inicial == "sim":
    exibir_trailer()
    escolha_final = pergunta_final()
    resposta_final(escolha_final)
  elif escolha_inicial == "não":
    print("\nSem problema, talvez em outra oportunidade.")
  else:
    print("\nResposta inválida. Tente novamente.")

if __name__ == "__main__":
  main()